name: covid_prediction_app_ios
description: A aovid prediction mobile application with IOS style UI.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.1
  flutter_spinkit: ^5.0.0
  url_launcher: ^6.0.3
  provider: ^5.0.0
  syncfusion_flutter_maps: ^19.1.63-beta
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - world.json
  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/FontsFree-Net-SFProText-Regular.ttf
        - asset: assets/fonts/FontsFree-Net-SFProText-Bold.ttf
        - asset: assets/fonts/FontsFree-Net-SFProDisplay-Semibold.ttf